13 Спринт
Selin-Eglence/Playlist5 pull request #5
Opened 2024-07-17 23:05 UTC by Selin-Eglence

2024-07-18 21:27 UTC, DmitrijEgorow requested changes

2024-07-18 21:27 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlist5/MediaActivity.kt
> +        year.text=track.releaseDate.substring(0, 4)
Перед коммитом стоит приводить файлы к правильному стилю, так как код будут смотреть другие разработчики. В студии это легко делать путём вызова горячей комбинации клавиш (она зависит от ОС), её можно посмотреть в меню Code → Reformat Code

2024-07-18 21:27 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlist5/MediaActivity.kt
> +            .transform(RoundedCorners(8))
Нужно вынести константу

2024-07-18 21:27 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlist5/SearchActivity.kt
>                  "Track: " + track.artistName + " - " + track.trackName,
Зачем тост?

2024-07-18 21:27 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlist5/SearchActivity.kt
>      companion object {
companion обычно идёт в конце класса

Подробнее описано в [документации](https://kotlinlang.org/docs/coding-conventions.html#class-layout)

2024-07-18 21:27 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlist5/Track.kt
> +    val artworkUrl1: String
Нужно переименовать

2024-07-18 21:27 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_media.xml
> +            android:id="@+id/light_mode"
Иной стиль наименования идентификатора, в других местах camelCase, стоит унифицировать

2024-07-18 21:27 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_media.xml
> +
Много пустых строк

2024-07-18 21:27 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlist5/MediaActivity.kt
> +@Suppress("DEPRECATION")
Зачем?

2024-07-18 21:27 UTC, DmitrijEgorow commented
- [ ] Стрелка возврата уехала сильно вправо

![Screenshot_20240719_001746](https://github.com/user-attachments/assets/91cc05ed-40d1-4950-871d-5333cc7931a6)

2024-07-18 21:28 UTC, DmitrijEgorow commented
- [ ] Разметку нужно делать адаптивной
<img width="400" alt="Screenshot 2024-07-19 at 00 19 26" src="https://github.com/user-attachments/assets/7f565c4c-00c6-46d2-868c-ed26d6763591">

2024-07-24 16:19 UTC, DmitrijEgorow commented
> * [ ]  Стрелка возврата уехала сильно вправо
> 
> ![Screenshot_20240719_001746](https://private-user-images.githubusercontent.com/36837067/350153365-91cc05ed-40d1-4950-871d-5333cc7931a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzY2MTgsIm5iZiI6MTcyMTgzNjMxOCwicGF0aCI6Ii8zNjgzNzA2Ny8zNTAxNTMzNjUtOTFjYzA1ZWQtNDBkMS00OTUwLTg3MWQtNTMzM2NjNzkzMWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE1NTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYzg1YmNjYjU4ZmUyNjhhZjZmYjdkOTBiNDczOWM0Y2EzZTZkODNmOTBkMzg1NGFhMDM5YmIxYmJlNjg2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u007AQsWraQgXX5jzqTtWNd4sGuAq9z5_xK9VfqpSW4)

Актуально

2024-07-24 17:06 UTC, Selin-Eglence commented
если вы приложили скрин, то он по каким то причинам не открывается

2024-08-11 10:45 UTC, merged